In [ ]:
#Ex1 - Leia uma cadeia de caracteres no formato “DD/MM/AAAA” e 
#copie o dia, mês e ano para três variáveis inteiras

data=(input('introduza uma data no formato DD/MM/AAA: '))
dia, mes, ano = [int(i) for i in data.split("/")]
print("dia =", dia, "mes =",mes, "ano =",ano)


dia = 12 mes = 12 ano = 2032


In [3]:
#Ex2 - Escreve uma função em Python que dada uma palavra retorne o número de vogais nessa palavra.

def contar_vogais(palavra):
    vogais="aeiouAEIOU"
    soma=0
    for i in vogais:
        conta=palavra.count(i)
        soma=conta+soma
    return soma

palavra=input('Digite 1 palavra: ')

soma_vogais=contar_vogais(palavra)
print(palavra)
print(f"número de vogais é {soma_vogais}")


abelha
número de vogais é 3


In [37]:
#Ex3 - Escreve uma função em Python que dada uma lista de números imprime 
# a soma dos valores dessa lista, o número de elementos da lista e a media desses valores.
# Implementa tratamento de exceções no teu código (try…except…else..finally).

def calcula_lista(lista):
    try:
        # Converte os elementos da lista para inteiros
        numeros = [int(num) for num in lista]
        
        # Calcular soma, tamanho e média
        soma = sum(numeros)
        tamanho = len(numeros)
        media = soma / tamanho
        
    except ValueError:
        print("Erro: A lista contém valores não numéricos.")
    except ZeroDivisionError:
        print("Erro: Não é possível calcular a média de uma lista vazia.")
    else:
        # Executado se nenhum erro ocorrer
        print(numeros)
        print("Soma da lista:", soma)
        print("Número de elementos da lista:", tamanho)
        print("Média dos valores da lista:", format(media, ".2f"))
    finally:
        print("Operação terminada.")

# Entrada do usuário
texto = input("Insira uma sequência de números separados por espaços: ")
print(texto)
lista = texto.split() #converte texto em lista
print(lista)

# executar a função
calcula_lista(lista)



56 89 -78 89 -2
['56', '89', '-78', '89', '-2']
[56, 89, -78, 89, -2]
Soma da lista: 154
Número de elementos da lista: 5
Média dos valores da lista: 30.80
Operação terminada.


In [ ]:
#4.	Utilizando a biblioteca NumPy:
    #a.	Cria um array de números 1 com shape (8, 2)
    #b.	Cria um array de zeros com shape (5, 7)
    #c.	Subtraia o novo array de outro com dados aleatórios e armazene o numa variável chamada subarray
    #d.	Calcula a média dos valores do array subarray

import numpy as np
import random
matrz1= np.array ([[1,1,1,1,1,1,1, 1],
                   [1,1,1,1,1,1,1,1]])
matrz2= np.array ([[0,0,0,0,0], 
                   [0,0,0,0,0], 
                   [0,0,0,0,0],
                   [0,0,0,0,0],
                   [0,0,0,0,0]])
matrzA= np.random.randint(1,100, size=(5,4))                                                                                                                        
matrzB= np.random.randint(1,100, size=(5,4)) 
subarray= matrzA - matrzB
media_subarray=np.mean(subarray)
print(matrzA)
print (matrzB)
print(subarray)
print(media_subarray)


[[31 73 75 65]
 [82 73 59 18]
 [65 34 89 23]
 [87 13 31 72]
 [18 87 47 41]]
[[61 55 35 99]
 [ 7 35 27 54]
 [66 33 54 77]
 [75 79 11  7]
 [78 95 37 13]]
[[-30  18  40 -34]
 [ 75  38  32 -36]
 [ -1   1  35 -54]
 [ 12 -66  20  65]
 [-60  -8  10  28]]
4.25
